version: '3.7'
services:
  postgres:
    image: postgres:14.2
    environment:
      - POSTGRES_USER=ledger
      - POSTGRES_PASSWORD=ledger
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data