CREATE TABLE area_afetada
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    residencial          VARCHAR(255),
    comercial            VARCHAR(255),
    industrial           VARCHAR(255),
    agricola             VARCHAR(255),
    pecuaria             VARCHAR(255),
    extrativismo_vegetal VARCHAR(255),
    reserva_florestal    VARCHAR(255),
    mineracao            VARCHAR(255),
    turismo_outras       VARCHAR(255),
    ocorrencia_id        INTEGER                                  NOT NULL,
    CONSTRAINT pk_area_afetada PRIMARY KEY (id)
);

CREATE TABLE cobrade
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    categoria VARCHAR(255),
    grupo     VARCHAR(255),
    subgrupo  VARCHAR(255),
    tipo      VARCHAR(255),
    subtipo   VARCHAR(255),
    definicao VARCHAR(255),
    codigo    VARCHAR(255),
    CONSTRAINT pk_cobrade PRIMARY KEY (id)
);

CREATE TABLE dano_tipos
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    categoria VARCHAR(255),
    descricao VARCHAR(255),
    CONSTRAINT pk_dano_tipos PRIMARY KEY (id)
);

CREATE TABLE danos
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ocorrencia_id INTEGER                                 NOT NULL,
    latitude      VARCHAR(30)                             NOT NULL,
    longitude     VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_danos PRIMARY KEY (id)
);

CREATE TABLE danos_ambientais
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo               INTEGER,
    populacao_atingida INTEGER,
    dano_id            BIGINT                                   NOT NULL,
    CONSTRAINT pk_danos_ambientais PRIMARY KEY (id)
);

CREATE TABLE danos_fotos
(
    dano_id BIGINT NOT NULL,
    foto    OID
);

CREATE TABLE danos_humanos
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo           INTEGER,
    numero_pessoas INTEGER,
    dano_id        BIGINT                                   NOT NULL,
    CONSTRAINT pk_danos_humanos PRIMARY KEY (id)
);

CREATE TABLE danos_materiais
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo      INTEGER,
    destruido BOOLEAN,
    descricao BOOLEAN,
    valor     DECIMAL,
    dano_id   BIGINT,
    CONSTRAINT pk_danos_materiais PRIMARY KEY (id)
);

CREATE TABLE instituicao_informante
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ocorrencia_id INTEGER                                 NOT NULL,
    nome          VARCHAR(255),
    responsavel   VARCHAR(255),
    CONSTRAINT pk_instituicao_informante PRIMARY KEY (id)
);

CREATE TABLE instituicao_informante_telefones
(
    instituicao_informante_id BIGINT NOT NULL,
    telefone                  VARCHAR(20)
);

CREATE TABLE ocorrencia
(
    id                     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data                   TIMESTAMP WITHOUT TIME ZONE,
    municipio              VARCHAR(255),
    uf                     VARCHAR(255),
    defesa_civil_informada BOOLEAN,
    sedec_informado        BOOLEAN,
    cobrade_id             INTEGER                                  NOT NULL,
    latitude               VARCHAR(30)                              NOT NULL,
    longitude              VARCHAR(30)                              NOT NULL,
    CONSTRAINT pk_ocorrencia PRIMARY KEY (id)
);

CREATE TABLE ufs
(
    id	    INTEGER NOT NULL,
    sigla	VARCHAR(2) NOT NULL UNIQUE,
    nome	VARCHAR(21) NOT NULL
);

CREATE TABLE municipios
(
    id	    INTEGER NOT NULL,
    nome    VARCHAR(300) NOT NULL,
    uf	    VARCHAR(2) NOT NULL
);

ALTER TABLE area_afetada
    ADD CONSTRAINT FK_AREA_AFETADA_ON_OCORRENCIA FOREIGN KEY (ocorrencia_id) REFERENCES ocorrencia (id);

ALTER TABLE danos_ambientais
    ADD CONSTRAINT FK_DANOS_AMBIENTAIS_ON_DANO FOREIGN KEY (dano_id) REFERENCES danos (id);

ALTER TABLE danos_humanos
    ADD CONSTRAINT FK_DANOS_HUMANOS_ON_DANO FOREIGN KEY (dano_id) REFERENCES danos (id);

ALTER TABLE danos_materiais
    ADD CONSTRAINT FK_DANOS_MATERIAIS_ON_DANO FOREIGN KEY (dano_id) REFERENCES danos (id);

ALTER TABLE danos
    ADD CONSTRAINT FK_DANOS_ON_OCORRENCIA FOREIGN KEY (ocorrencia_id) REFERENCES ocorrencia (id);

ALTER TABLE instituicao_informante
    ADD CONSTRAINT FK_INSTITUICAO_INFORMANTE_ON_OCORRENCIA FOREIGN KEY (ocorrencia_id) REFERENCES ocorrencia (id);

ALTER TABLE ocorrencia
    ADD CONSTRAINT FK_OCORRENCIA_ON_COBRADE FOREIGN KEY (cobrade_id) REFERENCES cobrade (id);

ALTER TABLE danos_fotos
    ADD CONSTRAINT fk_danos_fotos_on_dano FOREIGN KEY (dano_id) REFERENCES danos (id);

ALTER TABLE instituicao_informante_telefones
    ADD CONSTRAINT fk_instituicao_informante_telefones_on_instituicao_informante FOREIGN KEY (instituicao_informante_id) REFERENCES instituicao_informante (id);

ALTER TABLE municipios
    ADD CONSTRAINT FK_MUNICIPIOS_ON_UFS FOREIGN KEY (uf) REFERENCES ufs (sigla);