INSERT INTO
    ledger.ledger.cobrade
    (categoria, grupo, subgrupo, tipo, subtipo, definicao, codigo)
    VALUES
           ('Naturais', 'Geológico', 'Terremoto', 'Tremor de terra', null, '', '11110'),
           ('Naturais', 'Geológico', 'Terremoto', 'Tsunami', null, '', '11120'),
           ('Naturais', 'Geológico', 'Emanação Vulcânica', null, null, '', '11200'),
           ('Naturais', 'Geológico', 'Movimento de massa', 'Quedas, tombamentos e rolamentos', 'Blocos', '', '11311'),
           ('Naturais', 'Geológico', 'Movimento de massa', 'Quedas, tombamentos e rolamentos', 'Lascas', '', '11312'),
           ('Naturais', 'Geológico', 'Movimento de massa', 'Quedas, tombamentos e rolamentos', 'Matacães', '', '11313'),
           ('Naturais', 'Geológico', 'Movimento de massa', 'Quedas, tombamentos e rolamentos', 'Lajes', '', '11314'),
           ('Naturais', 'Geológico', 'Movimento de massa', 'Deslizamentos', 'Deslizamentos de solo e/ou rocha', '',
            '11321'),
           ('Naturais', 'Geológico', 'Movimento de massa', 'Corridas de massa', 'Solo/Lama', '', '11331'),
           ('Naturais', 'Geológico', 'Movimento de massa', 'Corridas de massa', 'Rocha/Detrito', '', '11332'),
           ('Naturais', 'Geológico', 'Movimento de massa', 'Subsidências e colapsos', null, '', '11340'),
           ('Naturais', 'Geológico', 'Erosão', 'Erosão costeira/Marinha', null, '', '11410'),
           ('Naturais', 'Geológico', 'Erosão', 'Erosão de margem fluvial', null, '', '11429'),
           ('Naturais', 'Geológico', 'Erosão', 'Erosão continental', 'Laminar', '', '11431'),
           ('Naturais', 'Geológico', 'Erosão', 'Erosão continental', 'Ravinas', '', '11432'),
           ('Naturais', 'Geológico', 'Erosão', 'Erosão continental', 'Boçorocas', '', '11433'),
           ('Naturais', 'Hidrológico', null, null, null, '', '12100'),
           ('Naturais', 'Hidrológico', null, null, null, '', '12200'),
           ('Naturais', 'Hidrológico', null, null, null, '', '12300'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13111'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13112'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13120'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13211'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13212'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13213'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13214'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13215'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13310'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13321'),
           ('Naturais', 'Meteorológico', null, null, null, '', '13322'),
           ('Naturais', 'Climatológico', null, null, null, '', '14110'),
           ('Naturais', 'Climatológico', null, null, null, '', '14120'),
           ('Naturais', 'Climatológico', null, null, null, '', '14131'),
           ('Naturais', 'Climatológico', null, null, null, '', '14132'),
           ('Naturais', 'Climatológico', null, null, null, '', '14140'),
           ('Naturais', 'Biológico', null, null, null, '', '15110'),
           ('Naturais', 'Biológico', null, null, null, '', '15120'),
           ('Naturais', 'Biológico', null, null, null, '', '15130'),
           ('Naturais', 'Biológico', null, null, null, '', '15140'),
           ('Naturais', 'Biológico', null, null, null, '', '15210'),
           ('Naturais', 'Biológico', null, null, null, '', '15221'),
           ('Naturais', 'Biológico', null, null, null, '', '15222'),
           ('Naturais', 'Biológico', null, null, null, '', '15230'),
           ('Tecnológicos', 'Desastres relacionados a substâncias radioativas', null, null, null, '', '21110'),
           ('Tecnológicos', 'Desastres relacionados a substâncias radioativas', null, null, null, '', '21210'),
           ('Tecnológicos', 'Desastres relacionados a substâncias radioativas', null, null, null, '', '21310'),
           ('Tecnológicos', 'Desastres relacionados a produtos perigosos', null, null, null, '', '22110'),
           ('Tecnológicos', 'Desastres relacionados a produtos perigosos', null, null, null, '', '22210'),
           ('Tecnológicos', 'Desastres relacionados a produtos perigosos', null, null, null, '', '22220'),
           ('Tecnológicos', 'Desastres relacionados a produtos perigosos', null, null, null, '', '22310'),
           ('Tecnológicos', 'Desastres relacionados a produtos perigosos', null, null, null, '', '22410'),
           ('Tecnológicos', 'Desastres relacionados a produtos perigosos', null, null, null, '', '22420'),
           ('Tecnológicos', 'Desastres relacionados a produtos perigosos', null, null, null, '', '22430'),
           ('Tecnológicos', 'Desastres relacionados a produtos perigosos', null, null, null, '', '22440'),
           ('Tecnológicos', 'Desastres relacionados a produtos perigosos', null, null, null, '', '22450'),
           ('Tecnológicos', 'Desastres relacionados a produtos perigosos', null, null, null, '', '22460'),
           ('Tecnológicos', 'Desastres relacionados a incêndios urbanos', null, null, null, '', '23110'),
           ('Tecnológicos', 'Desastres relacionados a incêndios urbanos', null, null, null, '', '23120'),
           ('Tecnológicos', 'Desastres relacionados a incêndios urbanos', null, null, null, '', '24100'),
           ('Tecnológicos', 'Desastres relacionados a incêndios urbanos', null, null, null, '', '24200'),
           ('Tecnológicos', 'Desastres relacionados a transporte de passageiros e cargas não perigosas', null, null,
            null, '', '25100'),
           ('Tecnológicos', 'Desastres relacionados a transporte de passageiros e cargas não perigosas', null, null,
            null, '', '25200'),
           ('Tecnológicos', 'Desastres relacionados a transporte de passageiros e cargas não perigosas', null, null,
            null, '', '25300'),
           ('Tecnológicos', 'Desastres relacionados a transporte de passageiros e cargas não perigosas', null, null,
            null, '', '25400'),
           ('Tecnológicos', 'Desastres relacionados a transporte de passageiros e cargas não perigosas', null, null,
            null, '', '25500');

INSERT INTO ledger.ledger.dano_tipos
    (categoria, descricao)
VALUES ('ambiental', 'Contaminação do Ar'),
       ('ambiental', 'Contaminação do Água'),
       ('ambiental', 'Contaminação do Solo'),
       ('ambiental', 'Exaurimento Hídrico'),
       ('ambiental', 'Incêndio APA'),
       ('material', 'Unidade Habitacionais'),
       ('material', 'Instalações Públicas de Saúde'),
       ('material', 'Instalações Públicas de Ensino'),
       ('material', 'Instalações Públicas Prestadoras de Serviços'),
       ('material', 'Instalações Públicas Prestadoras de Uso Comunitário'),
       ('material', 'Obras de Infra Estrutura Públicas'),
       ('humano', 'Mortos'),
       ('humano', 'Feridos'),
       ('humano', 'Enfermos'),
       ('humano', 'Desabrigados'),
       ('humano', 'Desalojados'),
       ('humano', 'Desaparecidos'),
       ('humano', 'Outros Afetados');
